export const PUBLIC_USER_SELECT = {
    id: true,
    name: true,
    bio: true,
    profilePhoto: true,
    residence: true,
    lat: true,
    lng: true,
    city: true,
    country: true,
    role: true,
    careTypes: true,
    availability: true,
    displayMode: true,
    dateOfBirth: true,
    createdAt: true,
    updatedAt: true,
    averageRating: true,
    reviewCount: true,
} as const;
